### ISSUE TITLE
v2 MsgBoxButtonNames

### ISSUE THREAD

**Issue by mmikeww** [Lexikos/AutoHotkey_L-Docs#171]
The new [MsgBox help page](https://lexikos.github.io/v2/docs/commands/MsgBox.htm) still links to the old [MsgBoxButtonNames script](https://lexikos.github.io/v2/docs/scripts/MsgBoxButtonNames.htm) . Perhaps you want to remove that link or update that script with the new v2 syntax

**Comment by Lexikos** [comment]
Perhaps I want someone else to do it.

**None** of the scripts in the showcase have been updated (in a long time, or at all for v2). In general, I haven't updated all examples either, only examples on each page that I update (such as on the MsgBox page).  Partly it's because there's a chance that the language will change before final release and they will have to be updated again, and partly because I only have so much motivation, and documenting the details is more important.

I never personally used the script showcase. That, combined with a general lack of motivation, means I will likely remove it if no one volunteers to update it.

**Comment by mmikeww** [comment]
Of course, fair enough

**Comment by Ragnar-F** [comment]
> None of the scripts in the showcase have been updated (in a long time, or at all for v2).

Well, that's not true. I had updated all the code examples on Jul 2016 for 2.0-a075-02fab78, including the script showcase. See closed pull request: #139 

I'll check and fix them again.

**Comment by Lexikos** [comment]
Right, I forgot, as I did none of it myself, for the reasons I mentioned above. Thanks.
