### ISSUE TITLE
while %x% different from while % x or while x

### ISSUE THREAD

**Issue by wyagd001** [Lexikos/AutoHotkey_L-Docs#189]
`if %x%` `msgbox %x%` `while %x%` are easily confused with poor consistency

Not mentioned in the document (except for Changes & New Features).

example 1
```
qq=4

q::
while %qq%
{
qq -=1
msgbox %qq%
}
return
```
example 2
```
qq=4

q::
if %qq%
{
qq -=1
msgbox %qq%
}
return
```

example 3
```
qq=4

q::
while % qq
{
qq -=1
msgbox %qq%
}
return
```
example 4
```
qq=w
w=5
q::
while %qq%
{
qq -=1
msgbox %qq%
}
return
```

example 5
```
qq=w
w=5
q::
while % qq
{
qq -=1
msgbox %qq%
}
return
```

**Comment by Lexikos** [comment]
While accepts an expression. MsgBox does not accept an expression. If accepts several different things. The syntax of each command is described in the documentation, and is clearly not expected to be identical between these three commands.

I agree that the inconsistency is confusing, but I disagree with the notion that these specific examples should be "mentioned in the document". Each command follows a specific set of rules, and these rules are shared by groups of commands, not unique to these three. If follows the same rules as other legacy commands which accept expressions, MsgBox follows the same rules as other commands which *don't* accept expressions, and While/For/Until/Throw are newer commands which only accept pure expressions.

Recent v2-alpha releases have addressed these issues by making the syntax more consistent - see [Removal of command syntax](https://autohotkey.com/boards/viewtopic.php?f=37&t=31139). That topic also provides links to (incomplete) revised documentation which attempts to clarify the v1 syntax.

If someone can provide more specific suggestions of actual changes (such as via a pull request), I would consider them. Otherwise, I have no intention of addressing this other than via the revision mentioned above.
