### ISSUE TITLE
ISO-8859-1 vs UTF-8

### ISSUE THREAD

**Issue by joedf** [Lexikos/AutoHotkey_L-Docs#249]
The docs is currently using "ISO-8859-1" instead of "UTF-8". Is there a particular reason for this?
Currently the docs' search box does not work because the key name `mört` within var `SearchIndex` (near "mywindowtitle") is being loaded as `mÃ¶rt` instead in [this file ](https://github.com/Lexikos/AutoHotkey_L-Docs/blob/v2/docs/static/source/data_search.js). This flags an invalid character error, and so on:
```js
SyntaxError: illegal character @ data_search.js:1:157034
ReferenceError: SearchIndex is not defined @ content.js:111:7
```
I have double checked that the files on the server are encoded as UTF-8 without BOM (content.js is ASCII since there are no unicode chars used).

**Comment by Ragnar-F** [comment]
I remember that CHM's standard sidebar didn't handle UTF-8 content well. Non-ASCII characters were displayed incorrectly in the search results, etc. (of course, this problem was never relevant for the English language, because it does not contain such characters). Now, however, with the new sidebar, there is no reason not to switch to UTF-8.

But why this problem is currently occurring is not quite clear to me. I haven't changed anything about that. Normally data_search.js should be encoded as UTF-8 **with** BOM. The line `FileEncoding "UTF-8"` in build_search.ahk (AHK v2 script) is responsible for this. Either something went wrong when this file was created or the server automatically changed the encoding of this file.

For testing purposes you could encode data_search.js as UTF-8 with BOM and upload it on the server to see if it works again. Meanwhile I will change the charset of the .htm pages to UTF-8.

**Comment by joedf** [comment]
I have added the BOM manually to `data_search.js`. Now the search works just fine after a hard-refresh.
`sed -i '1s/^/\xef\xbb\xbf/' data_search.js`

Interestingly, I've read that one should not include the UTF-8 BOM in unicode files as per specs and recommendations. Another source says it is optional... No matter, the new change #250 should fix this either way. 👍 

For further reading:
https://stackoverflow.com/a/15691902/883015
https://stackoverflow.com/a/30349775/883015

**Comment by Ragnar-F** [comment]
Thanks. At the moment the search only works for [https://<ins>**www**</ins>.autohotkey.com/docs/](https://www.autohotkey.com/docs/) but not for https://autohotkey.com/docs/. But I suppose this discrepancy will eventually resolve itself automatically at some point.

**Comment by joedf** [comment]
That's interesting... It works for me on both, but you're probably right.
