### ISSUE TITLE
Ambiguous phrasing in Library list on Functions page

### ISSUE THREAD

**Issue by Vismund-Cygnus** [Lexikos/AutoHotkey_L-Docs#299]
Reference: https://autohotkey.com/docs/Functions.htm#lib

The list of libraries has:

```
%A_ScriptDir%\Lib\  ; Local library - requires [v1.0.90+].
%A_MyDocuments%\AutoHotkey\Lib\  ; User library.
path-to-the-currently-running-AutoHotkey.exe\Lib\  ; Standard library.
```

but shouldn't that third line be something like:

```
directory-of-the-currently-running-AutoHotkey.exe\Lib\`  ; Standard library.
```
or even:
```
% StrReplace(A_AhkPath, "AutoHotkey.exe", "Lib\") ; Standard library
```

EDIT: Apologies, I just now noticed the [Docs suggestions](https://autohotkey.com/boards/viewtopic.php?f=13&t=1434) on the forum. I'd delete this if I could but otherwise I'll be posting these sorta things there because filing an issue on Github doesn't seem like the better way to go about it.

**Comment by Ragnar-F** [comment]
There's nothing wrong with opening up the issues here. Personally, I very much welcome this, simply because it makes it easier to manage these issues.

Although `path-to-` is not incorrect in a certain sense (but `path-of-` would be), I'll implement your first suggestion in hope of reducing confusion. The second suggestion would be too complicated to understand for beginners.
