### ISSUE TITLE
The hyperlink is not valid in the code text

### ISSUE THREAD

**Issue by wyagd001** [Lexikos/AutoHotkey_L-Docs#351]
For example, in the file Scripts.htm, the <a href="#continuation_quotes">automatically escaped</a> is not valid.

<pre><em>; EXAMPLE #1:</em>
Var := "
(
Line 1 of the text.
Line 2 of the text. By default, a linefeed (`n) is present between lines.
Additionally, "quote marks" are <a href="#continuation_quotes">automatically escaped</a> when appropriate.
)"

**Comment by Ragnar-F** [comment]
This is intended in favor of the syntax highlighter. Otherwise, the syntax recognizer in content.js would become too complicated, which could lead to poor performance and less readability. However, inside comments and single-line quoted strings, links are still "allowed".

The only current solution would be to slightly change the affected places to make important links inside codes visible.
