### ISSUE TITLE
Help compiler error when using compile_chm.ahk

### ISSUE THREAD

**Issue by white-gthb** [Lexikos/AutoHotkey_L-Docs#620]
To be able to see the error, change the line:
> https://github.com/AutoHotkey/AutoHotkeyDocs/blob/b0b9833dbed155b2705aaf17561da09e34af281e/compile_chm.ahk#L39
> Add `cmd /k call "..."`:
```
RunWait cmd /k call "%hhc%" "%A_ScriptDir%\Project.hhp"
```

\
Help compiler error when using `compile_chm.ahk`:

> HHC5003: Error: Compilation failed while compiling docs\..
>
> The following files were not compiled:
> docs\.

\
This is caused by the line:
> https://github.com/AutoHotkey/AutoHotkeyDocs/blob/b0b9833dbed155b2705aaf17561da09e34af281e/docs/index.htm#L8

This line was added when `docs/AutoHotkey.htm` was renamed to `docs/index.htm`, see [docs/AutoHotkey.htm → docs/index.htm](https://github.com/AutoHotkey/AutoHotkeyDocs/commit/94ad126dd0e54fbe4faee99b61e0564d813898e3#diff-9663b92adc3334341bc0082aefd9a2ed1ad3cd2b0c63e7dcad2dce1f29ce4b0f).
It doesn't seem to cause any harm, but why was the line added?

**Comment by jcunews** [comment]
The canonical link HTML tag is for search engine optimization. To avoid creating duplicate entries or processing duplicate files.

But the URL for the `href` attribute should not be `.`, because the `.` as well as `..` are relative names which refer to a directory instead of a file.

While the actual resource for a directory URL may resolve to e.g. `index.html` or any other file name (depending on the web server's default directory index file setting), it will not point to the current file if the current file's name is not e.g. `index.html`.

So, the URL for the `href` attribute should be an exact file name of the current file. Just like the value of the `content` attribute of the old `ahk:equiv-v2` meta HTML tag. Either do that, or remove the canonical link HTML tag entirely.
